# AMSAB Worker — auto-generated runner
# Task: extract ingredients and steps from search results
# Tool: python_interpreter
import json, sys, os

ARGS = {
  "code": "import base64 as _b64\nnode_1_output = _b64.b64decode(\"eyJzdGF0dXMiOiAib2siLCAib3V0cHV0IjogInN0ZXAtYnktc3RlcCBiaXJ5YW5pIHJlY2lwZSBhdCBEdWNrRHVja0dvICZuYnNwOyBEdWNrRHVja0dvICZuYnNwOyBBbGwgUmVnaW9ucyBBcmdlbnRpbmEgQXVzdHJhbGlhIEF1c3RyaWEgQmVsZ2l1bSAoZnIpIEJlbGdpdW0gKG5sKSBCcmF6aWwgQnVsZ2FyaWEgQ2FuYWRhIChlbikgQ2FuYWRhIChmcikgQ2F0YWxvbmlhIENoaWxlIENoaW5hIENvbG9tYmlhIENyb2F0aWEgQ3plY2ggUmVwdWJsaWMgRGVubWFyayBFc3RvbmlhIEZpbmxhbmQgRnJhbmNlIEdlcm1hbnkgR3JlZWNlIEhvbmcgS29uZyBIdW5nYXJ5IEljZWxhbmQgSW5kaWEgKGVuKSBJbmRvbmVzaWEgKGVuKSBJcmVsYW5kIElzcmFlbCAoZW4pIEl0YWx5IEphcGFuIEtvcmVhIExhdHZpYSBMaXRodWFuaWEgTWFsYXlzaWEgKGVuKSBNZXhpY28gTmV0aGVybGFuZHMgTmV3IFplYWxhbmQgTm9yd2F5IFBha2lzdGFuIChlbikgUGVydSBQaGlsaXBwaW5lcyAoZW4pIFBvbGFuZCBQb3J0dWdhbCBSb21hbmlhIFJ1c3NpYSBTYXVkaSBBcmFiaWEgU2luZ2Fwb3JlIFNsb3Zha2lhIFNsb3ZlbmlhIFNvdXRoIEFmcmljYSBTcGFpbiAoY2EpIFNwYWluIChlcykgU3dlZGVuIFN3aXR6ZXJsYW5kIChkZSkgU3dpdHplcmxhbmQgKGZyKSBUYWl3YW4gVGhhaWxhbmQgKGVuKSBUdXJrZXkgVVMgKEVuZ2xpc2gpIFVTIChTcGFuaXNoKSBVa3JhaW5lIFVuaXRlZCBLaW5nZG9tIFZpZXRuYW0gKGVuKSBBbnkgVGltZSBQYXN0IERheSBQYXN0IFdlZWsgUGFzdCBNb250aCBQYXN0IFllYXIgJm5ic3A7ICZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOyAmbmJzcDsgMS4mbmJzcDsgQ2hpY2tlbiBCaXJ5YW5pICggU3RlcC1ieS1zdGVwIENoaWNrZW4gQmlyeWFuaSkgLSBSdWNoaXNraXRjaGVuICZuYnNwOyZuYnNwOyZuYnNwOyBUaGUgdHJhZGl0aW9uYWwgQ2hpY2tlbiBCaXJ5YW5pIHJlY2lwZSBhcHBlYXJzIGludHJpY2F0ZSBvd2luZyB0byB0aGUgZXh0ZW5zaXZlIGxpc3Qgb2YgaW5ncmVkaWVudHMgYW5kIGVsYWJvcmF0ZSBjb29raW5nIHRlY2huaXF1ZXMsIHdoaWNoIHN0b3BzIG1hbnkgZnJvbSBhdHRlbXB0aW5nIGl0IGF0IGhvbWUuIEJ1dCwgSSBoYXZlIHRyaWVkIHRvIGRpc3BlbCB0aGF0IG15dGggYW5kIHNpbXBsaWZpZWQgdGhlIHByb2Nlc3Mgb2YgbWFraW5nIGF1dGhlbnRpYyBiaXJ5YW5pIHRvIGhlbHAgeW91IGNyZWF0ZSB0aGlzIGN1bGluYXJ5IG1hc3RlcnBpZWNlIHdpdGggY29uZmlkZW5jZS4gJm5ic3A7Jm5ic3A7Jm5ic3A7IHd3dy5ydWNoaXNraXRjaGVuLmNvbS9jaGlja2VuLWJpcnlhbmkvICZuYnNwOyAmbmJzcDsgMi4mbmJzcDsgQXV0aGVudGljIENoaWNrZW4gQmlyeWFuaSBSZWNpcGUgU3RlcCBieSBTdGVwOiBVbHRpbWF0ZSBGbGF2b3IgR3VpZGUgJm5ic3A7Jm5ic3A7Jm5ic3A7IFRoaXMgYXV0aGVudGljIGNoaWNrZW4gYmlyeWFuaSByZWNpcGUgYnJlYWtzIGRvd24gZXZlcnkgc3RlcCAsIG1ha2luZyBpdCBlYXN5IGZvciB5b3UgdG8gY3JlYXRlIGEgZmxhdm9yZnVsLCBhcm9tYXRpYyBkaXNoIGF0IGhvbWUuIEltYWdpbmUgdGhlIHJpY2ggc3BpY2VzLCB0ZW5kZXIgY2hpY2tlbiwgYW5kIGZsdWZmeSByaWNlIGNvbWluZyB0b2dldGhlciBwZXJmZWN0bHlcdTIwMTRyaWdodCBmcm9tIHlvdXIgb3duIGtpdGNoZW4uIEtlZXAgcmVhZGluZywgYW5kIHlvdSYjeDI3O2xsIGRpc2NvdmVyIHNpbXBsZSB0aXBzIHRoYXQgd2lsbCB0dXJuIHlvdXIgYmlyeWFuaSBpbnRvIGEgZmFtaWx5IGZhdm9yaXRlLiAmbmJzcDsmbmJzcDsmbmJzcDsgY2hpY2tlbmNvb2t0ZW1wLmNvbS9hdXRoZW50aWMtY2hpY2tlbi1iaXJ5YW5pLXJlY2lwZS1zdGVwLWJ5LXN0ZXAvICZuYnNwOyAmbmJzcDsgMy4mbmJzcDsgQ2hpY2tlbiBCaXJ5YW5pIFJlY2lwZTogU3RlcC1ieS1TdGVwIENvb2tpbmcgSW5zdHJ1Y3Rpb25zICZuYnNwOyZuYnNwOyZuYnNwOyBMZWFybiBhbiBlYXN5IGNoaWNrZW4gYmlyeWFuaSByZWNpcGUgd2l0aCBzaW1wbGUgc3RlcHMgLiBNYWtlIGEgdGFzdHkgSW5kaWFuIHJpY2UgZGlzaCBhdCBob21lIHVzaW5nIHNwaWNlcyBhbmQgY2hpY2tlbiwgd2l0aCBhIHN0ZXAtYnktc3RlcCBndWlkZS4gJm5ic3A7Jm5ic3A7Jm5ic3A7IG5hdHVyZXMtc3BpY2UuY29tL2NoaWNrZW4tYmlyeWFuaS1yZWNpcGUtc3RlcC1ieS1zdGVwLWNvb2tpbmcvICZuYnNwOyAmbmJzcDsgNC4mbmJzcDsgRWFzeSBDaGlja2VuIEJpcnlhbmkgKFNob3J0Y3V0IFJlY2lwZSkgLSBGb29kZXNzICZuYnNwOyZuYnNwOyZuYnNwOyBIb3cgdG8gTWFrZSBTaG9ydGN1dCBDaGlja2VuIEJpcnlhbmkgOiBBbiBFYXN5IEd1aWRlIFNpbXBsZSBzdGVwcyAsIGNvenkgYW5kIGRlbGljaW91cyBwYXlvZmYuIEl0JiN4Mjc7cyB3ZWVrbmlnaHQtZnJpZW5kbHkgYW5kIGJpZyBvbiBmbGF2b3IuIChUcnkgbXkgbGlmZS1jaGFuZ2luZyBidXR0ZXIgY2hpY2tlbiByZWNpcGUgLCB0b28hKSBNYXJpbmF0ZSB0aGUgQ2hpY2tlbiBUb3NzIGNoaWNrZW4gd2l0aCBsZW1vbiwgZ2FybGljLCBnYXJhbSBtYXNhbGEsIGFuZCBzYWx0LiBTZXQgYXNpZGUgd2hpbGUgeW91IHByZXAgb25pb25zIGFuZCByaWNlLiBRdWljayBtYXJpbmF0aW5nIHdvcmtzIGhlcmUuICZuYnNwOyZuYnNwOyZuYnNwOyBmb29kZXNzLmNvbS9lYXN5LWJpcnlhbmktcmVjaXBlLyAmbmJzcDsgJm5ic3A7IDUuJm5ic3A7IEVhc3kgQ2hpY2tlbiBCaXJ5YW5pIFJlY2lwZSAtIFN0ZXAtYnktU3RlcCBHdWlkZSBmb3IgQmVnaW5uZXJzICZuYnNwOyZuYnNwOyZuYnNwOyBDaGlja2VuIEJpcnlhbmkgaXMgb25lIG9mIHRoZSBtb3N0IGJlbG92ZWQgZGlzaGVzIGluIEluZGlhbiBjdWlzaW5lLCBrbm93biBmb3IgaXRzIHJpY2ggZmxhdm9ycywgZnJhZ3JhbnQgc3BpY2VzLCBhbmQgdGVuZGVyLCBqdWljeSBjaGlja2VuIHBpZWNlcy4gTWFueSBob21lIGNvb2tzIGZlZWwgaW50aW1pZGF0ZWQgYnkgdGhlIHByb2Nlc3MsIGJ1dCB3aXRoIHRoZSByaWdodCBzdGVwcyAsIG1ha2luZyBjaGlja2VuIGJpcnlhbmkgYXQgaG9tZSBjYW4gYmUgc3RyYWlnaHRmb3J3YXJkIGFuZCBpbmNyZWRpYmx5IHJld2FyZGluZy4gVGhpcyBzdGVwLWJ5LXN0ZXAgZ3VpZGUgd2lsbCBzaG93IHlvdSBob3cgdG8gbWFrZSBhbiBhdXRoZW50aWMgY2hpY2tlbiBiaXJ5YW5pIHRoYXQmI3gyNztzIGZ1bGwgLi4uICZuYnNwOyZuYnNwOyZuYnNwOyByZWNpcGlieXRlcy5jb20vaW5kaWFuLXJlY2lwZXMvcmljZS1yZWNpcGVzL2Vhc3ktaG9tZW1hZGUtY2hpY2tlbi1iaXJ5YW5pLXJlY2lwZS1zdGVwLWJ5LXN0ZXAtZ3VpZGUtZm9yLWJlZ2lubmVycy8gJm5ic3A7ICZuYnNwOyA2LiZuYnNwOyBBdXRoZW50aWMgQ2hpY2tlbiBCaXJ5YW5pIFJlY2lwZSB8IFN0ZXAtYnktU3RlcCBHdWlkZSAmbmJzcDsmbmJzcDsmbmJzcDsgQXV0aGVudGljIENoaWNrZW4gQmlyeWFuaSBSZWNpcGUgd2l0aCBiYXNtYXRpIHJpY2UsIHRlbmRlciBjaGlja2VuLCBhbmQgcmljaCBzcGljZXMuIEVhc3kgc3RlcC1ieS1zdGVwIG1ldGhvZCBmb3IgcGVyZmVjdCBiaXJ5YW5pIGV2ZXJ5IHRpbWUuICZuYnNwOyZuYnNwOyZuYnNwOyBmYWhvcmlhLmNvbS9hdXRoZW50aWMtY2hpY2tlbi1iaXJ5YW5pLXJlY2lwZS1wZXJmZWN0LWZsYXZvci8gJm5ic3A7ICZuYnNwOyA3LiZuYnNwOyBDaGlja2VuIEJpcnlhbmkgfCBJbmRpYW4gT25lLVBvdCBSaWNlIEFuZCBDaGlja2VuIChWaWRlbykgJm5ic3A7Jm5ic3A7Jm5ic3A7IExlYXJuIGhvdyB0byBtYWtlIGF1dGhlbnRpYyBjaGlja2VuIGJpcnlhbmkgYXQgaG9tZSB3aXRoIHRoaXMgc3RlcC1ieS1zdGVwIHJlY2lwZSB1c2luZyB0aGUgdHJhZGl0aW9uYWwgZHVtIG1ldGhvZC4gSW5jbHVkZXMgdGlwcywgc3Vic3RpdHV0aW9ucywgYW5kIHBybyB0ZWNobmlxdWVzIGZvciBwZXJmZWN0IHJlc3VsdHMgZXZlcnkgdGltZS4gJm5ic3A7Jm5ic3A7Jm5ic3A7IHd3dy5wYW50c2Rvd25hcHJvbnNvbi5jb20vY2hpY2tlbi1iaXJ5YW5pLXJlY2lwZS8gJm5ic3A7ICZuYnNwOyA4LiZuYnNwOyBDaGlja2VuIEJpciJ9\").decode()\ndata = $node_1_output$$ print('Ingredients:'), print(data[:1000])"
}

def run(args):
    import io, contextlib, json as _json
    code = args.get("code", args.get("script", "")).strip()
    input_data = args.get("input", "")
    if not code:
        return "Error: no code provided in args"
    buf = io.StringIO()
    local_vars = {"INPUT": input_data, "json": _json}
    try:
        compiled = compile(code, "<amsab>", "exec")
    except SyntaxError as e:
        lines = code.split("\n")
        bad = lines[e.lineno - 1].strip() if e.lineno and e.lineno <= len(lines) else "?"
        raise SyntaxError(f"line {e.lineno}: {e.msg} — code: {bad!r}")
    with contextlib.redirect_stdout(buf):
        exec(compiled, local_vars)
    stdout = buf.getvalue().strip()
    output_var = local_vars.get("OUTPUT", "")
    result = stdout or (str(output_var) if output_var else "")
    return result if result else "(no output — add print() calls to your code)"

if __name__ == "__main__":
    try:
        result = run(ARGS)
        print(json.dumps({"status": "ok", "output": result}))
    except Exception as exc:
        print(json.dumps({"status": "error", "error": str(exc)}))
        sys.exit(1)
