# AMSAB Worker — auto-generated runner
# Task: extract relevant stock data from search results
# Tool: python_interpreter
import json, sys, os

ARGS = {
  "code": "import base64 as _b64\nnode_1_output = _b64.b64decode(\"eyJzdGF0dXMiOiAib2siLCAib3V0cHV0IjogInNob3J0IHRlcm0gZ2FpbnMgc3RvY2tzIGluZGlhIGF0IER1Y2tEdWNrR28gJm5ic3A7IER1Y2tEdWNrR28gJm5ic3A7IEFsbCBSZWdpb25zIEFyZ2VudGluYSBBdXN0cmFsaWEgQXVzdHJpYSBCZWxnaXVtIChmcikgQmVsZ2l1bSAobmwpIEJyYXppbCBCdWxnYXJpYSBDYW5hZGEgKGVuKSBDYW5hZGEgKGZyKSBDYXRhbG9uaWEgQ2hpbGUgQ2hpbmEgQ29sb21iaWEgQ3JvYXRpYSBDemVjaCBSZXB1YmxpYyBEZW5tYXJrIEVzdG9uaWEgRmlubGFuZCBGcmFuY2UgR2VybWFueSBHcmVlY2UgSG9uZyBLb25nIEh1bmdhcnkgSWNlbGFuZCBJbmRpYSAoZW4pIEluZG9uZXNpYSAoZW4pIElyZWxhbmQgSXNyYWVsIChlbikgSXRhbHkgSmFwYW4gS29yZWEgTGF0dmlhIExpdGh1YW5pYSBNYWxheXNpYSAoZW4pIE1leGljbyBOZXRoZXJsYW5kcyBOZXcgWmVhbGFuZCBOb3J3YXkgUGFraXN0YW4gKGVuKSBQZXJ1IFBoaWxpcHBpbmVzIChlbikgUG9sYW5kIFBvcnR1Z2FsIFJvbWFuaWEgUnVzc2lhIFNhdWRpIEFyYWJpYSBTaW5nYXBvcmUgU2xvdmFraWEgU2xvdmVuaWEgU291dGggQWZyaWNhIFNwYWluIChjYSkgU3BhaW4gKGVzKSBTd2VkZW4gU3dpdHplcmxhbmQgKGRlKSBTd2l0emVybGFuZCAoZnIpIFRhaXdhbiBUaGFpbGFuZCAoZW4pIFR1cmtleSBVUyAoRW5nbGlzaCkgVVMgKFNwYW5pc2gpIFVrcmFpbmUgVW5pdGVkIEtpbmdkb20gVmlldG5hbSAoZW4pIEFueSBUaW1lIFBhc3QgRGF5IFBhc3QgV2VlayBQYXN0IE1vbnRoIFBhc3QgWWVhciAmbmJzcDsgJm5ic3A7Jm5ic3A7Jm5ic3A7Jm5ic3A7ICZuYnNwOyAxLiZuYnNwOyBMaXN0IG9mIFNob3J0IFRlcm0gU3RvY2tzIGluIEluZGlhIDIwMjYgLSBzbWFsbGNhc2UgJm5ic3A7Jm5ic3A7Jm5ic3A7IEhlcmUgaXMgYSBsaXN0IG9mIHNob3J0IHRlcm0gc3RvY2tzIGluIEluZGlhIGZvciAyMDI2LCB3aXRoIGluc2lnaHRzIGludG8gY29tcGFuaWVzLCBsaXZlIHNoYXJlIHByaWNlLCBhbmQgZmFjdG9ycyB0byBjb25zaWRlciBiZWZvcmUgaW52ZXN0aW5nLiAmbmJzcDsmbmJzcDsmbmJzcDsgd3d3LnNtYWxsY2FzZS5jb20vbGlzdHMvc2hvcnQtdGVybS1zdG9ja3MvICZuYnNwOyAmbmJzcDsgMi4mbmJzcDsgQmVzdCBTaG9ydCBUZXJtIFN0b2NrcyB0byBCdXkgaW4gSW5kaWEgMjAyNiB8IDVwYWlzYSAmbmJzcDsmbmJzcDsmbmJzcDsgQmVzdCBzaG9ydCB0ZXJtIHN0b2NrcyB0byBidXkgaW4gSW5kaWEgZm9yIDIwMjYuIEdldCBpbnNpZ2h0cyBvbiB0b3AgcGlja3MsIHN0cmF0ZWdpZXMgYW5kIGtleSBmYWN0b3JzIHRvIG1heGltaXplIHNob3J0LXRlcm0gZ2FpbnMgLiAmbmJzcDsmbmJzcDsmbmJzcDsgd3d3LjVwYWlzYS5jb20vYmxvZy9iZXN0LXNob3J0LXRlcm0tc3RvY2tzLXRvLWJ1eS1pbi1pbmRpYSAmbmJzcDsgJm5ic3A7IDMuJm5ic3A7IExpc3Qgb2YgU2hvcnQgVGVybSBTdG9ja3MgaW4gSW5kaWEgMjAyNSAtIFRpY2tlcnRhcGUgJm5ic3A7Jm5ic3A7Jm5ic3A7IEhlcmUgaXMgdGhlIGNvbXBsZXRlIGxpc3Qgb2YgdGhlIHRvcCBzaG9ydCB0ZXJtIHN0b2NrcyBpbiBJbmRpYSAuIExlYXJuIGhvdyB0byBpZGVudGlmeSwgYW5kIHN0cmF0ZWdpZXMgZm9yIHNob3J0IHRlcm0gaW52ZXN0bWVudC4gJm5ic3A7Jm5ic3A7Jm5ic3A7IHd3dy50aWNrZXJ0YXBlLmluL2Jsb2cvYmVzdC1zaG9ydC10ZXJtLXN0b2Nrcy8gJm5ic3A7ICZuYnNwOyA0LiZuYnNwOyBMaXN0IG9mIFNob3J0IFRlcm0gSW52ZXN0bWVudCBTdG9ja3MgaW4gSW5kaWEgLSBEaGFuICZuYnNwOyZuYnNwOyZuYnNwOyBIZXJlIGlzIHRoZSBsaXN0IG9mIFNob3J0IFRlcm0gU3RvY2tzIC4gQ2hlY2sgb3V0IDUyVyBoaWdoIGFuZCBsb3csIFBFICZhbXA7IFBCIHJhdGlvLCBtYXJrZXQgY2FwLCBFUFMsIGV0YyBvZiBTaG9ydCBUZXJtIFNoYXJlcyBub3chICZuYnNwOyZuYnNwOyZuYnNwOyBkaGFuLmNvL3N0b2Nrcy9tYXJrZXQvc2hvcnQtdGVybS1zdG9ja3MvICZuYnNwOyAmbmJzcDsgNS4mbmJzcDsgU3RvY2tzIHRvIGJ1eSBmb3Igc2hvcnQgdGVybTogRnJvbSBDb2FsIEluZGlhIHRvIEZpbm9sZXggLi4uIC0gTVNOICZuYnNwOyZuYnNwOyZuYnNwOyBTdG9ja3MgdG8gYnV5OiBJbiBhIHR1cmJ1bGVudCBtYXJrZXQsIEppZ2FyIFBhdGVsIGZyb20gQW5hbmQgUmF0aGkgaWRlbnRpZmllcyB0aHJlZSBzdG9ja3MgLCBpbmNsdWRpbmcgQ29hbCBJbmRpYSBhbmQgRmlub2xleCBJbmR1c3RyaWVzLCBwb2lzZWQgZm9yIHNob3J0LXRlcm0gZ2FpbnMgLiBGb3IgdGhlIE5pZnR5IDUwLCBQYXRlbCAuLi4gJm5ic3A7Jm5ic3A7Jm5ic3A7IHd3dy5tc24uY29tL2VuLWluL21vbmV5L21hcmtldHMvc3RvY2tzLXRvLWJ1eS1mb3Itc2hvcnQtdGVybS1mcm9tLWNvYWwtaW5kaWEtdG8tZmlub2xleC1pbmR1c3RyaWVzLWppZ2FyLXBhdGVsLW9mLWFuYW5kLXJhdGhpLXN1Z2dlc3RzLTMtc2hhcmVzL2FyLUFBMVdxeVR5ICZuYnNwOyAmbmJzcDsgNi4mbmJzcDsgU3RvY2tzIHRvIGJ1eSBmb3Igc2hvcnQgdGVybTogRnJvbSBIQ0wgVGVjaCB0byBIaW5kdXN0YW4gWmluYyAuLi4gLSBNaW50ICZuYnNwOyZuYnNwOyZuYnNwOyBBcyB0aGUgSW5kaWFuIHN0b2NrIG1hcmtldCBmYWNlcyBoZWFkd2luZHMsIGV4cGVydHMgcmVjb21tZW5kIHNpeCBzdG9ja3MgcG9pc2VkIGZvciBzaG9ydC10ZXJtIGdhaW5zIC4gRnJvbSBIQ0wgVGVjaCYjeDI3O3MgYnJlYWtvdXQgdG8gSGluZHVzdGFuIFppbmMmI3gyNztzIGJ1bGxpc2ggbW9tZW50dW0sIGRpc2NvdmVyIHRoZXNlIHN0b2NrcyAuICZuYnNwOyZuYnNwOyZuYnNwOyB3d3cubGl2ZW1pbnQuY29tL21hcmtldC9zdG9jay1tYXJrZXQtbmV3cy9zdG9ja3MtdG8tYnV5LWZvci1zaG9ydC10ZXJtLWZyb20taGNsLXRlY2gtdG8taGluZHVzdGFuLXppbmMtZXhwZXJ0cy1yZWNvbW1lbmQtNi10ZWNobmljYWwtcGlja3MtZm9yLW5leHQtMS0yLXdlZWtzLTExNzY4ODc1MDcwOTYzLmh0bWwgJm5ic3A7ICZuYnNwOyA3LiZuYnNwOyBCZXN0IFNob3J0LVRlcm0gU3RvY2tzIEluIEluZGlhIC0gQXBwcmVjaWF0ZSAmbmJzcDsmbmJzcDsmbmJzcDsgRGlzY292ZXIgdGhlIGJlc3Qgc2hvcnQtdGVybSBzdG9ja3MgdG8gYnV5IGluIEluZGlhIC4gR2V0IGV4cGVydCBpbnNpZ2h0cyBvbiB0b3AtcGVyZm9ybWluZyBzdG9ja3MgZm9yIHF1aWNrIGdhaW5zIGFuZCBzbWFydCBpbnZlc3RtZW50cy4gJm5ic3A7Jm5ic3A7Jm5ic3A7IGFwcHJlY2lhdGV3ZWFsdGguY29tL2Jsb2cvc2hvcnQtdGVybS1zdG9ja3MtaW4taW5kaWEgJm5ic3A7ICZuYnNwOyA4LiZuYnNwOyBCZXN0IFNob3J0LVRlcm0gU3RvY2tzIHRvIEJ1eSBpbiBJbmRpYSAyMDI1IGZvciBGYXN0IFJldHVybnMgJm5ic3A7Jm5ic3A7Jm5ic3A7IExvb2tpbmcgZm9yIHRoZSBiZXN0IHNob3J0LXRlcm0gc3RvY2tzIGluIEluZGlhIGZvciAyMDI1PyBFeHBsb3JlIHRvcCBwaWNrcywgc2VjdG9yIHRyZW5kcywgdGVjaG5pY2FsIHNpZ25hbHMsIHJpc2tzLCBhbmQgZXhwZXJ0IHN0cmF0ZWdpZXMgZm9yIGZhc3RlciByZXR1cm5zLiAmbmJzcDsmbmJzcDsmbmJzcDsgbGVtb25uLmNvLmluL2Jsb2cvc3RvY2tzL2Jlc3Qtc2hvcnQtdGVybS1zdG9ja3MtaW5kaWEvICZuYnNwOyAmbmJzcDsgOS4mbmJzcDsgQmVzdCBTaG9ydC1UZXJtIFN0b2NrcyB0byBCdXkgVG9kYXkgaW4gMjAyNSAmbmJzcDsmbmJzcDsmbmJzcDsgRXhwbG9yaW5nIHNob3J0LXRlcm0gc3RvY2tzIHRvIGJ1eSBtaWdodCBlbmNvdXJhZ2UgaW52ZXN0b3JzIHRvIGVhcm4gcG90ZW50aWFsIGdhaW5zIGluIGEgc2hvcnQgdGltZSBwZXJpb2QgdHlwaWNhbGx5IGxlc3MgdGhhbiBhIHllYXIuIFRoZXkgY2FuIHdpdG5lc3MgcXVpY2sgcHJpY2UgbW92ZW1lbnRzIGJlY2F1c2Ugb2YgZWNvbm9taWMgdHJlbmRzLCBpbmR1c3RyeSB0cmVuZHMsIGFuZCBtYXJrZXQgdm9sYXRpbGl0eS4gU2hvcnQtdGVybSBzdG9ja3MgY291bGQgYmUgYSBzZWFtbGVzcyBvcHBvcnR1bml0eSBmb3IgaW52ZXN0b3JzIHdpdGggaGlnaC0ifQ==\").decode()\ndata = node_1_output\nprint('Short-term gain stocks in India:');\nfor line in data.split('\\n'): print(line[:100])"
}

def run(args):
    import io, contextlib, json as _json
    code = args.get("code", args.get("script", "")).strip()
    input_data = args.get("input", "")
    if not code:
        return "Error: no code provided in args"
    buf = io.StringIO()
    local_vars = {"INPUT": input_data, "json": _json}
    try:
        compiled = compile(code, "<amsab>", "exec")
    except SyntaxError as e:
        lines = code.split("\n")
        bad = lines[e.lineno - 1].strip() if e.lineno and e.lineno <= len(lines) else "?"
        raise SyntaxError(f"line {e.lineno}: {e.msg} — code: {bad!r}")
    with contextlib.redirect_stdout(buf):
        exec(compiled, local_vars)
    stdout = buf.getvalue().strip()
    output_var = local_vars.get("OUTPUT", "")
    result = stdout or (str(output_var) if output_var else "")
    return result if result else "(no output — add print() calls to your code)"

if __name__ == "__main__":
    try:
        result = run(ARGS)
        print(json.dumps({"status": "ok", "output": result}))
    except Exception as exc:
        print(json.dumps({"status": "error", "error": str(exc)}))
        sys.exit(1)
