# AMSAB Worker — auto-generated runner
# Task: extract key takeaways from search results
# Tool: python_interpreter
import json, sys, os

ARGS = {
  "code": "import base64 as _b64\nnode_1_output = _b64.b64decode(\"eyJzdGF0dXMiOiAib2siLCAib3V0cHV0IjogIm1vZGVybiBmdXJuaXR1cmUgZGVzaWduIGlkZWFzIGF0IER1Y2tEdWNrR28gJm5ic3A7IER1Y2tEdWNrR28gJm5ic3A7IEFsbCBSZWdpb25zIEFyZ2VudGluYSBBdXN0cmFsaWEgQXVzdHJpYSBCZWxnaXVtIChmcikgQmVsZ2l1bSAobmwpIEJyYXppbCBCdWxnYXJpYSBDYW5hZGEgKGVuKSBDYW5hZGEgKGZyKSBDYXRhbG9uaWEgQ2hpbGUgQ2hpbmEgQ29sb21iaWEgQ3JvYXRpYSBDemVjaCBSZXB1YmxpYyBEZW5tYXJrIEVzdG9uaWEgRmlubGFuZCBGcmFuY2UgR2VybWFueSBHcmVlY2UgSG9uZyBLb25nIEh1bmdhcnkgSWNlbGFuZCBJbmRpYSAoZW4pIEluZG9uZXNpYSAoZW4pIElyZWxhbmQgSXNyYWVsIChlbikgSXRhbHkgSmFwYW4gS29yZWEgTGF0dmlhIExpdGh1YW5pYSBNYWxheXNpYSAoZW4pIE1leGljbyBOZXRoZXJsYW5kcyBOZXcgWmVhbGFuZCBOb3J3YXkgUGFraXN0YW4gKGVuKSBQZXJ1IFBoaWxpcHBpbmVzIChlbikgUG9sYW5kIFBvcnR1Z2FsIFJvbWFuaWEgUnVzc2lhIFNhdWRpIEFyYWJpYSBTaW5nYXBvcmUgU2xvdmFraWEgU2xvdmVuaWEgU291dGggQWZyaWNhIFNwYWluIChjYSkgU3BhaW4gKGVzKSBTd2VkZW4gU3dpdHplcmxhbmQgKGRlKSBTd2l0emVybGFuZCAoZnIpIFRhaXdhbiBUaGFpbGFuZCAoZW4pIFR1cmtleSBVUyAoRW5nbGlzaCkgVVMgKFNwYW5pc2gpIFVrcmFpbmUgVW5pdGVkIEtpbmdkb20gVmlldG5hbSAoZW4pIEFueSBUaW1lIFBhc3QgRGF5IFBhc3QgV2VlayBQYXN0IE1vbnRoIFBhc3QgWWVhciAmbmJzcDsgJm5ic3A7Jm5ic3A7Jm5ic3A7Jm5ic3A7ICZuYnNwOyAxLiZuYnNwOyBNb2Rlcm4gTGl2aW5nIFJvb20gSWRlYXMgJm5ic3A7Jm5ic3A7Jm5ic3A7IEJyb3dzZSBtb2Rlcm4gbGl2aW5nIHJvb20gZGVjb3JhdGluZyBpZGVhcyBhbmQgZnVybml0dXJlIGxheW91dHMuIERpc2NvdmVyIGRlc2lnbiBpbnNwaXJhdGlvbiBmcm9tIGEgdmFyaWV0eSBvZiBtb2Rlcm4gbGl2aW5nIHJvb21zLCBpbmNsdWRpbmcgY29sb3IsIGRlY29yIGFuZCBzdG9yYWdlIG9wdGlvbnMuICZuYnNwOyZuYnNwOyZuYnNwOyB3d3cuaG91enouY29tL3Bob3Rvcy9tb2Rlcm4tbGl2aW5nLXJvb20taWRlYXMtcGhicjEtYnB+dF83MTh+c18yMTA1ICZuYnNwOyAmbmJzcDsgMi4mbmJzcDsgMTcgTXVzdC1TZWUgTW9kZXJuIEludGVyaW9yIERlc2lnbiBJZGVhcyBmb3IgYSBTb3BoaXN0aWNhdGVkIExvb2sgJm5ic3A7Jm5ic3A7Jm5ic3A7IE1vZGVybiBpbnRlcmlvciBkZXNpZ24gZm9jdXNlcyBvbiBjbGVhbiBsaW5lcywgZnVuY3Rpb25hbGl0eSwgYW5kIG5hdHVyYWwgbWF0ZXJpYWxzLiBEaXNjb3ZlciBtb2Rlcm4gaW50ZXJpb3IgaWRlYXMgdGhhdCBhcmUgd2FybSwgbGl2YWJsZSwgYW5kIGN1cnJlbnQuICZuYnNwOyZuYnNwOyZuYnNwOyB3d3cudGhlc3BydWNlLmNvbS9tb2Rlcm4taW50ZXJpb3ItZGVzaWduLWlkZWFzLTExNzA1NTYzICZuYnNwOyAmbmJzcDsgMy4mbmJzcDsgNzUgRGVzaWduZXItQXBwcm92ZWQgTW9kZXJuIExpdmluZyBSb29tIElkZWFzIGZvciAyMDI1ICZuYnNwOyZuYnNwOyZuYnNwOyBUaGVzZSA3NSBtb2Rlcm4gbGl2aW5nIHJvb20gaWRlYXMgZnJvbSBkZXNpZ25lciBob21lcyB3aWxsIGluc3BpcmUgeW91IHRvIHJlZnJlc2ggYW5kIHVwZGF0ZSB5b3VyIHNwYWNlIHNvIHlvdSBjYW4gYXBwcmVjaWF0ZSB5b3VyIGZhdm9yaXRlIGdhdGhlcmluZyBzcG90IGFuZXcuICZuYnNwOyZuYnNwOyZuYnNwOyB3d3cuaG91c2ViZWF1dGlmdWwuY29tL3Jvb20tZGVjb3JhdGluZy9saXZpbmctZmFtaWx5LXJvb21zL2c0Njc3NDE2NC9tb2Rlcm4tbGl2aW5nLXJvb20tZGVzaWduLWlkZWFzLyAmbmJzcDsgJm5ic3A7IDQuJm5ic3A7IDM1IE1vZGVybiBMaXZpbmcgUm9vbSBJZGVhcyBmb3IgYSBDb250ZW1wb3JhcnkgWWV0IFRpbWVsZXNzIFNwYWNlICZuYnNwOyZuYnNwOyZuYnNwOyBNb2Rlcm4gZGVzaWduIGlzIGtub3duIGZvciBpdHMgc3RyZWFtbGluZWQgc2hhcGVzLCBmdW5jdGlvbmFsIGxheW91dHMsIG5hdHVyYWwgYWNjZW50cywgYW5kIHVuZnVzc3kgcHJhY3RpY2FsaXR5LiBUaGUgcm9vbXMgb24gdGhpcyBsaXN0IG9mZmVyIGluc3BpcmF0aW9uIGZvciBiYWxhbmNpbmcgbW9kZXJuIGVsZW1lbnRzXHUyMDFhIGxpa2Ugc2xpbSBzb2ZhcyBhbmQgYWJzdHJhY3QgYXJ0d29yaywgdG8gaG9tZXMgdGhhdCBhcmUgdHJhZGl0aW9uYWwsIGNvbnRlbXBvcmFyeSwgb3IgYW55d2hlcmUgaW4gYmV0d2Vlbi4gJm5ic3A7Jm5ic3A7Jm5ic3A7IHd3dy5tYXJ0aGFzdGV3YXJ0LmNvbS9tb2Rlcm4tbGl2aW5nLXJvb20taWRlYXMtODU5ODA5NSAmbmJzcDsgJm5ic3A7IDUuJm5ic3A7IE1vZGVybiBGdXJuaXR1cmUgRGVzaWduIElkZWFzICZhbXA7IFRyZW5kcyBmb3IgMjAyNiB8IEFORCBBY2FkZW15ICZuYnNwOyZuYnNwOyZuYnNwOyBFeHBsb3JlIG1vZGVybiBmdXJuaXR1cmUgZGVzaWduIGlkZWFzIGFuZCB0cmVuZHMgZm9yIDIwMjYuIExlYXJuIGFib3V0IHN1c3RhaW5hYmxlIG1hdGVyaWFscywgc3R5bGVzLCBhbmQgdGlwcyBmb3IgY3JlYXRpbmcgZnVuY3Rpb25hbCwgc3R5bGlzaCBpbnRlcmlvcnMuICZuYnNwOyZuYnNwOyZuYnNwOyB3d3cuYW5kYWNhZGVteS5jb20vcmVzb3VyY2VzL2Jsb2cvaW50ZXJpb3ItZGVzaWduL21vZGVybi1mdXJuaXR1cmUtZGVzaWduLXRyZW5kcy8gJm5ic3A7ICZuYnNwOyA2LiZuYnNwOyAxNSBNb2Rlcm4gRnVybml0dXJlIHdpdGggYSBDcmVhdGl2ZSBUd2lzdCAtIEhvbWVkaXQgJm5ic3A7Jm5ic3A7Jm5ic3A7IFNvbWUgcGVvcGxlIGRvbiYjeDI3O3QgYXNzb2NpYXRlIG1vZGVybiBmdXJuaXR1cmUgaWRlYXMgd2l0aCBjb21mb3J0LCBidXQgdGhlIFNpZW5uYSBhcm1jaGFpciBieSBTdHVkaW8gQmFsdXR0byBmb3IgSG9ybSB3aWxsIGNvbnZpbmNlIHRoZW0gb3RoZXJ3aXNlLiBJbnNwaXJlZCBieSBTd2VkaXNoIGRlc2lnbnMgZnJvbSB0aGUgMTk3MHMsIHRoZSBjaGFpciBoYXMgYSBzb2xpZCBibGFjayBhc2ggd29vZGVuIGJhc2UgdGhhdCBzdXBwb3J0cyB0aGUgcGFkZGVkIGFuZCB1cGhvbHN0ZXJlZCBzaGVsbCB3aG9zZSBmcm9udCBpcyBnZW50bHkgdGlwcGVkIHVwd2FyZCBmb3IgY29tZm9ydC4gJm5ic3A7Jm5ic3A7Jm5ic3A7IHd3dy5ob21lZGl0LmNvbS9jcmVhdGl2ZS1tb2Rlcm4tZnVybml0dXJlLWlkZWFzLyAmbmJzcDsgJm5ic3A7IDcuJm5ic3A7IEZ1cm5pdHVyZSBEZXNpZ246IEh1bmRyZWRzIG9mIElkZWFzIG9mIE1vZGVybiBEZXNpZ25lciBGdXJuaXR1cmUgJm5ic3A7Jm5ic3A7Jm5ic3A7IEluIHRoZSBGdXJuaXR1cmUgRGVzaWduIHNlY3Rpb24sIHlvdSBjYW4gZmluZCBodW5kcmVkcyBvZiBkZXNpZ24gb2YgZnVybml0dXJlIGlkZWFzIG1hZGUgaW4gdmFyaW91cyBzdHlsZXMgYW5kIGRpcmVjdGlvbnM6IHNjYW5kaW5hdmlhbiBkZXNpZ24gZnVybml0dXJlICwgaW5kdXN0cmlhbCBmdXJuaXR1cmUgZGVzaWduICwgbW9kZXJuIHdvb2RlbiBmdXJuaXR1cmUgZGVzaWduICwgb2ZmaWNlIGZ1cm5pdHVyZSBkZXNpZ24gYW5kIG90aGVycy4gRnVybml0dXJlIGlzIHRoZSBtb3N0IGltcG9ydGFudCBkZXRhaWwgaW4gdGhlIGZvcm1hdGlvbiBvZiBpbnRlcmlvciBkZXNpZ24gaW4gYWJzb2x1dGVseSBhbnkgcHJlbWlzZXMgLSBmcm9tIHByaXZhdGUgaG9tZXMgYW5kIG9mZmljZXMgdG8gLi4uICZuYnNwOyZuYnNwOyZuYnNwOyB3d3cuYmVhdXRpZnVsbGlmZS5pbmZvL2ludGVyaW9yLWRlc2lnbi9mdXJuaXR1cmUtZGVzaWduLyAmbmJzcDsgJm5ic3A7IDguJm5ic3A7IDkwKyBNb2Rlcm4gRnVybml0dXJlIERlc2lnbiBJZGVhcyB3aXRoIFBpY3R1cmVzIC0gSEFUSUwgJm5ic3A7Jm5ic3A7Jm5ic3A7IEtlZXAgaW4gbWluZCB0aGF0IHlvdXIgZGVzaWduIGFuZCBpZGVhcyBkZXBlbmQgb24geW91ciBzdHlsZSBhbmQgdGFzdGUuIExldCYjeDI3O3MgdGFrZSBhIGxvb2sgYXQgOTArIG1vZGVybiBmdXJuaXR1cmUgZGVzaWduIGlkZWFzIHdpdGggcGljdHVyZXMuIExpdmluZyBSb29tICJ9\").decode()\ndata = node_1_output\nprint('Key Takeaways:')\nprint(data[:2000])"
}

def run(args):
    import io, contextlib, json as _json
    code = args.get("code", args.get("script", "")).strip()
    input_data = args.get("input", "")
    if not code:
        return "Error: no code provided in args"
    buf = io.StringIO()
    local_vars = {"INPUT": input_data, "json": _json}
    try:
        compiled = compile(code, "<amsab>", "exec")
    except SyntaxError as e:
        lines = code.split("\n")
        bad = lines[e.lineno - 1].strip() if e.lineno and e.lineno <= len(lines) else "?"
        raise SyntaxError(f"line {e.lineno}: {e.msg} — code: {bad!r}")
    with contextlib.redirect_stdout(buf):
        exec(compiled, local_vars)
    stdout = buf.getvalue().strip()
    output_var = local_vars.get("OUTPUT", "")
    result = stdout or (str(output_var) if output_var else "")
    return result if result else "(no output — add print() calls to your code)"

if __name__ == "__main__":
    try:
        result = run(ARGS)
        print(json.dumps({"status": "ok", "output": result}))
    except Exception as exc:
        print(json.dumps({"status": "error", "error": str(exc)}))
        sys.exit(1)
