# AMSAB Worker — auto-generated runner
# Task: extract relevant data from search results
# Tool: python_interpreter
import json, sys, os

ARGS = {
  "code": "import base64 as _b64\nnode_1_output = _b64.b64decode(\"eyJzdGF0dXMiOiAib2siLCAib3V0cHV0IjogInJlc3RhdXJhbnQgaW5kdXN0cnkgdHJlbmRzLCBzdGF0aXN0aWNzLCBhbmQgYmVzdCBwcmFjdGljZXMgYXQgRHVja0R1Y2tHbyAmbmJzcDsgRHVja0R1Y2tHbyAmbmJzcDsgQWxsIFJlZ2lvbnMgQXJnZW50aW5hIEF1c3RyYWxpYSBBdXN0cmlhIEJlbGdpdW0gKGZyKSBCZWxnaXVtIChubCkgQnJhemlsIEJ1bGdhcmlhIENhbmFkYSAoZW4pIENhbmFkYSAoZnIpIENhdGFsb25pYSBDaGlsZSBDaGluYSBDb2xvbWJpYSBDcm9hdGlhIEN6ZWNoIFJlcHVibGljIERlbm1hcmsgRXN0b25pYSBGaW5sYW5kIEZyYW5jZSBHZXJtYW55IEdyZWVjZSBIb25nIEtvbmcgSHVuZ2FyeSBJY2VsYW5kIEluZGlhIChlbikgSW5kb25lc2lhIChlbikgSXJlbGFuZCBJc3JhZWwgKGVuKSBJdGFseSBKYXBhbiBLb3JlYSBMYXR2aWEgTGl0aHVhbmlhIE1hbGF5c2lhIChlbikgTWV4aWNvIE5ldGhlcmxhbmRzIE5ldyBaZWFsYW5kIE5vcndheSBQYWtpc3RhbiAoZW4pIFBlcnUgUGhpbGlwcGluZXMgKGVuKSBQb2xhbmQgUG9ydHVnYWwgUm9tYW5pYSBSdXNzaWEgU2F1ZGkgQXJhYmlhIFNpbmdhcG9yZSBTbG92YWtpYSBTbG92ZW5pYSBTb3V0aCBBZnJpY2EgU3BhaW4gKGNhKSBTcGFpbiAoZXMpIFN3ZWRlbiBTd2l0emVybGFuZCAoZGUpIFN3aXR6ZXJsYW5kIChmcikgVGFpd2FuIFRoYWlsYW5kIChlbikgVHVya2V5IFVTIChFbmdsaXNoKSBVUyAoU3BhbmlzaCkgVWtyYWluZSBVbml0ZWQgS2luZ2RvbSBWaWV0bmFtIChlbikgQW55IFRpbWUgUGFzdCBEYXkgUGFzdCBXZWVrIFBhc3QgTW9udGggUGFzdCBZZWFyICZuYnNwOyAmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsgJm5ic3A7IDEuJm5ic3A7IFBERiBTdGF0ZSBvZiBUaGUgUmVzdGF1cmFudCBJbmR1c3RyeSAyMDI1ICZuYnNwOyZuYnNwOyZuYnNwOyBUaGUgQXNzb2NpYXRpb24mI3gyNztzIHJlc2VhcmNoIGlzIGNvbnNpZGVyZWQgdGhlIHNvdXJjZSBmb3IgcmVzdGF1cmFudCBpbmR1c3RyeSBzYWxlcyBwcm9qZWN0aW9ucyBhbmQgSXQgaXMgYmFzZWQgb24gYW5hbHlzaXMgb2YgdGhlIGxhdGVzdCBlY29ub21pYyBkYXRhIGV4dGVuc2l2ZSBzdXJ2ZXlzIG9mIHJlc3RhdXJhbnQgb3BlcmF0b3JzIGFuZCAmbmJzcDsmbmJzcDsmbmJzcDsgZ28ucmVzdGF1cmFudC5vcmcvcnMvMDc4LVpMQS00NjEvaW1hZ2VzL1NPSS0yMDI1LVJlcG9ydC5wZGY/dmVyc2lvbj0wICZuYnNwOyAmbmJzcDsgMi4mbmJzcDsgVGhlIHRvcCByZXN0YXVyYW50IGluZHVzdHJ5IHRyZW5kcyBmb3IgMjAyNiB8IE1jS2luc2V5ICZuYnNwOyZuYnNwOyZuYnNwOyBBIG5ldyBkZXRhaWxlZCBNY0tpbnNleSBhbmFseXNpcyBsb29rcyBhdCB0aGUgbGF0ZXN0IHJlc3RhdXJhbnQgaW5kdXN0cnkgdHJlbmRzIHRoYXQgYXJlIHBvaXNlZCB0byByZXNoYXBlIHRoZSBjb25zdW1lciBsYW5kc2NhcGUgaW4gMjAyNiBhbmQgYmV5b25kLiAmbmJzcDsmbmJzcDsmbmJzcDsgd3d3Lm1ja2luc2V5LmNvbS9pbmR1c3RyaWVzL3JldGFpbC9vdXItaW5zaWdodHMvd2hhdC11cy1jb25zdW1lcnMtd2FudC1mcm9tLXJlc3RhdXJhbnRzLWluLTIwMjYgJm5ic3A7ICZuYnNwOyAzLiZuYnNwOyAzMCsgUmVzdGF1cmFudCBJbmR1c3RyeSBUcmVuZHMgYW5kIFN0YXRpc3RpY3MgLSBTY290dG1heC5jb20gJm5ic3A7Jm5ic3A7Jm5ic3A7IEZhY3QgY2hlY2tlZCB8IFRoZSByZXN0YXVyYW50IGluZHVzdHJ5IGlzIHBvaXNlZCBmb3Igc2lnbmlmaWNhbnQgZ3Jvd3RoIGluIHJlY2VudCB5ZWFycywgd2l0aCBzYWxlcyBwcm9qZWN0ZWQgdG8gcmVhY2ggJDEuNSB0cmlsbGlvbiBhbmQgZW1wbG95bWVudCBleHBlY3RlZCB0byBpbmNyZWFzZSBieSAyMDAsMDAwIGpvYnMsIHRvdGFsaW5nIDE1LjkgbWlsbGlvbiB3b3JrZXJzIG5hdGlvbndpZGUuIFRoaXMgZ3Jvd3RoIGlzIGRyaXZlbiBieSBzdHJvbmcgY29uc3VtZXIgZGVtYW5kIGFuZCBhIGZvY3VzIG9uIGVuaGFuY2luZyBkaW5pbmcgZXhwZXJpZW5jZXMgdGhyb3VnaCBpbm5vdmF0aW9uLCB0ZWNobm9sb2d5LCBhbmQgdmFsdWUuIEhvd2V2ZXIsLi4uICZuYnNwOyZuYnNwOyZuYnNwOyBzY290dG1heC5jb20vcmVzZWFyY2gvcmVzdGF1cmFudC1pbmR1c3RyeS10cmVuZHMvICZuYnNwOyAmbmJzcDsgNC4mbmJzcDsgUERGIFJFU1RBVVJBTlQgSU5EVVNUUlkgSU5TSUdIVFMgLSBjb2xlbWFucmVwb3J0LmNvbSAmbmJzcDsmbmJzcDsmbmJzcDsgU09DSUFMIE1FRElBJiN4Mjc7UyBHUk9XSU5HIElORkxVRU5DRSBPTiBNT0RFUk4gRElOSU5HIFRSRU5EUyBJbiAyMDI0LCBzb2NpYWwgbWVkaWEgcmVtYWluZWQgYSBjcml0aWNhbCBkcml2ZXIgb2YgY29uc3VtZXIgYmVoYXZpb3IgaW4gdGhlIHJlc3RhdXJhbnQgaW5kdXN0cnkgLCBwcm9mb3VuZGx5IGluZmx1ZW5jaW5nIGV2ZXJ5dGhpbmcgZnJvbSBtZW51IGRlc2lnbiB0byBicmFuZCBsb3lhbHR5LiBQbGF0Zm9ybXMgbGlrZSBJbnN0YWdyYW0sIFRpa1RvayBhbmQgRmFjZWJvb2sgaGF2ZSBiZWNvbWUgZXNzZW50aWFsIGNoYW5uZWxzIHRocm91Z2ggd2hpY2ggY29uc3VtZXJzIGRpc2NvdmVyIGFuZCBpbnRlcmFjdCB3aXRoIHJlc3RhdXJhbnRzICwgY29tcGVsbGluZyBvcGVyYXRvcnMgdG8gLi4uICZuYnNwOyZuYnNwOyZuYnNwOyBjb2xlbWFucmVwb3J0LmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAyNS8wMi9SZXN0YXVyYW50X0luc2lnaHRzX09yaWdpbmFsLWZpbGUtMS5wZGYgJm5ic3A7ICZuYnNwOyA1LiZuYnNwOyA1NSsgUmVzdGF1cmFudCBJbmR1c3RyeSBTdGF0aXN0aWNzIGZvciAyMDI1IC0gTWVudSBUaWdlciAmbmJzcDsmbmJzcDsmbmJzcDsgS25vd2xlZGdlIGFib3V0IGNoYW5nZXMgYW5kIHRyZW5kcyBpbiB0aGUgcmVzdGF1cmFudCBpbmR1c3RyeSB3aWxsIHNpZ25pZmljYW50bHkgaGVscCB5b3UgbWFrZSB3aXNlIGFuZCBpbmZvcm1lZCBkZWNpc2lvbi4gU3RheSB1cC10by1kYXRlIHdpdGggdGhlIGxhdGVzdCBkYXRhIG9uIHJlc3RhdXJhbnQgaW5kdXN0cnkgc3RhdGlzdGljcyBieSBhdHRlbmRpbmcgaW5kdXN0cnkgY29uZmVyZW5jZXMsIGZvbGxvd2luZyBpbmR1c3RyeSBleHBlcnRzIG9ubGluZSwgdGFsa2luZyB3aXRoIG90aGVyIG1hcmtldGVycywgYW5kIHJlYWRpbmcgYWJvdXQgaW5kdXN0cnkgcHVibGljYXRpb25zIGFuZCBibG9ncy4gJm5ic3A7Jm5ic3A7Jm5ic3A7IHd3dy5tZW51dGlnZXIuY29tL2Jsb2cvcmVzdGF1cmFudC1pbmR1c3RyeS1zdGF0aXN0aWNzICZuYnNwOyAmbmJzcDsgNi4mbmJzcDsgOTggUmVzdGF1cmFudCBJbmR1c3RyeSBTdGF0aXN0aWNzIFlvdSBTaG91bGQgS25vdyBpbiAyMDI1ICZuYnNwOyZuYnNwOyZuYnNwOyBEaXNjb3ZlciB0aGUga2V5IHJlc3RhdXJhbnQgaW5kdXN0cnkgc3RhdGlzdGljcyBmb3IgMjAyNS4gTGVhcm4gYWJvdXQgdGhlIGN1cnJlbnQgdHJlbmRzIGluIHNhbGVzLCBvcGVyYXRpb25zLCBjdXN0b21lciBiZWhhdmlvciwgYW5kIGV4cGVyaWVuY2UuICZuYnNwOyZuYnNwOyZuYnNwOyByZXprdS5jb20vYmxvZy9yZXN0YXVyYW50LWluZHVzdHJ5LXN0YXRpc3RpY3MvICZuYnNwOyAmbmJzcDsgNy4mbmJzcDsgVG9wIFJlc3RhdXJhbnQgSW5kdXN0cnkgVHJlbmRzIGluIDIwMjUgfCBTcXVhcmUgJm5ic3A7Jm5ic3A7Jm5ic3A7IEZyb20gYXV0b21hdGlvbiB0byBkaXZlcnNpZnlpbmcgcmV2ZW51ZSBzdHJlYW1zLCB0aGVzZSBhcmUgdGhlIG1vc3QgY29tcGVsbGluZyBnbG9iYWwgcmVzdGF1cmFudCB0cmVuZHMgc2hhcGluZyB0aGUgZm9vZCBhbmQgYmV2ZXJhZ2UgaW5kdXN0cnkgaW4gMjAyNS4gJm5ic3A7Jm5ic3A7Jm5ic3A7IHNxdWFyZXVwLmNvbS91cy9lbi90aGUtYm90dG9tLWxpbmUvc2VyaWVzL2ZvYy9yZXN0YXVyYW50LXRyZW5kcyAmbmJzcDsgJm5ic3A7IDguJm5ic3A7IFN0YXRlIG9mIHRoZSBSZXN0YXVyYW50IEluZHVzdHJ5IFJlcG9ydDogRGF0YSAmYW1wOyBTdGF0aXN0aWNzICZuYnNwOyZuYnNwOyZuYnNwOyBFeHBsb3JlIEJhbmsgb2YgQW1lcmljYSYjeDI3O3MgU3RhdGUgb2YgdGhlIFJlc3QifQ==\").decode()\ndata = node_1_output\nprint('Restaurant Industry Insights:')\nprint(data[:2000])"
}

def run(args):
    import io, contextlib, json as _json
    code = args.get("code", args.get("script", "")).strip()
    input_data = args.get("input", "")
    if not code:
        return "Error: no code provided in args"
    buf = io.StringIO()
    local_vars = {"INPUT": input_data, "json": _json}
    try:
        compiled = compile(code, "<amsab>", "exec")
    except SyntaxError as e:
        lines = code.split("\n")
        bad = lines[e.lineno - 1].strip() if e.lineno and e.lineno <= len(lines) else "?"
        raise SyntaxError(f"line {e.lineno}: {e.msg} — code: {bad!r}")
    with contextlib.redirect_stdout(buf):
        exec(compiled, local_vars)
    stdout = buf.getvalue().strip()
    output_var = local_vars.get("OUTPUT", "")
    result = stdout or (str(output_var) if output_var else "")
    return result if result else "(no output — add print() calls to your code)"

if __name__ == "__main__":
    try:
        result = run(ARGS)
        print(json.dumps({"status": "ok", "output": result}))
    except Exception as exc:
        print(json.dumps({"status": "error", "error": str(exc)}))
        sys.exit(1)
