# AMSAB Worker — auto-generated runner
# Task: analyze market data and insights
# Tool: python_interpreter
import json, sys, os

ARGS = {
  "code": "import base64 as _b64\nnode_1_output = _b64.b64decode(\"eyJzdGF0dXMiOiAib2siLCAib3V0cHV0IjogIkluZGlhbiBidXNpbmVzcyB0cmVuZHMgMjAyMy0yMDI1IGF0IER1Y2tEdWNrR28gJm5ic3A7IER1Y2tEdWNrR28gJm5ic3A7IEFsbCBSZWdpb25zIEFyZ2VudGluYSBBdXN0cmFsaWEgQXVzdHJpYSBCZWxnaXVtIChmcikgQmVsZ2l1bSAobmwpIEJyYXppbCBCdWxnYXJpYSBDYW5hZGEgKGVuKSBDYW5hZGEgKGZyKSBDYXRhbG9uaWEgQ2hpbGUgQ2hpbmEgQ29sb21iaWEgQ3JvYXRpYSBDemVjaCBSZXB1YmxpYyBEZW5tYXJrIEVzdG9uaWEgRmlubGFuZCBGcmFuY2UgR2VybWFueSBHcmVlY2UgSG9uZyBLb25nIEh1bmdhcnkgSWNlbGFuZCBJbmRpYSAoZW4pIEluZG9uZXNpYSAoZW4pIElyZWxhbmQgSXNyYWVsIChlbikgSXRhbHkgSmFwYW4gS29yZWEgTGF0dmlhIExpdGh1YW5pYSBNYWxheXNpYSAoZW4pIE1leGljbyBOZXRoZXJsYW5kcyBOZXcgWmVhbGFuZCBOb3J3YXkgUGFraXN0YW4gKGVuKSBQZXJ1IFBoaWxpcHBpbmVzIChlbikgUG9sYW5kIFBvcnR1Z2FsIFJvbWFuaWEgUnVzc2lhIFNhdWRpIEFyYWJpYSBTaW5nYXBvcmUgU2xvdmFraWEgU2xvdmVuaWEgU291dGggQWZyaWNhIFNwYWluIChjYSkgU3BhaW4gKGVzKSBTd2VkZW4gU3dpdHplcmxhbmQgKGRlKSBTd2l0emVybGFuZCAoZnIpIFRhaXdhbiBUaGFpbGFuZCAoZW4pIFR1cmtleSBVUyAoRW5nbGlzaCkgVVMgKFNwYW5pc2gpIFVrcmFpbmUgVW5pdGVkIEtpbmdkb20gVmlldG5hbSAoZW4pIEFueSBUaW1lIFBhc3QgRGF5IFBhc3QgV2VlayBQYXN0IE1vbnRoIFBhc3QgWWVhciAmbmJzcDsgJm5ic3A7Jm5ic3A7Jm5ic3A7Jm5ic3A7ICZuYnNwOyAxLiZuYnNwOyBJbmRpYSBlY29ub21pYyBvdXRsb29rIHwgRGVsb2l0dGUgSW5zaWdodHMgJm5ic3A7Jm5ic3A7Jm5ic3A7IFRocm91Z2ggMjAyNCBhbmQgZWFybHkgMjAyNSAsIEluZGlhIGV4cGVyaWVuY2VkIGFuIHVuZXhwZWN0ZWQgc2xvd2Rvd24gaW4gY3JlZGl0IGdyb3d0aCwgcGFydGljdWxhcmx5IGluIHBlcnNvbmFsIGxvYW5zIGFuZCBzbWFsbC0gYnVzaW5lc3MgbGVuZGluZy4gVGhlIFJCSSByZWNvZ25pemVkIHRoYXQsIHdpdGhvdXQgc3Ryb25nZXIgY3JlZGl0IHRyYW5zbWlzc2lvbiwgY29uc3VtZXIgc3BlbmRpbmcgcmVjb3Zlcnkgd291bGQgbG9zZSBtb21lbnR1bS4gJm5ic3A7Jm5ic3A7Jm5ic3A7IHd3dy5kZWxvaXR0ZS5jb20vdXMvZW4vaW5zaWdodHMvdG9waWNzL2Vjb25vbXkvYXNpYS1wYWNpZmljL2luZGlhLWVjb25vbWljLW91dGxvb2suaHRtbCAmbmJzcDsgJm5ic3A7IDIuJm5ic3A7IFRoZSBwcm9taXNlIG9mIGludGVybmF0aW9uYWwgYnVzaW5lc3MgZ3Jvd3RoIGluIEluZGlhIHwgTWNLaW5zZXkgJm5ic3A7Jm5ic3A7Jm5ic3A7IFN1Y2Nlc3Mgc3RvcmllcyBHbG9iYWwgaW50ZXJlc3QgaW4gSW5kaWEgaXMgYWxyZWFkeSBncm93aW5nLiBGcm9tIDIwMjEgdG8gMjAyMyAsIDk4NCBpbnRlcm5hdGlvbmFsIGNvbXBhbmllcyByZWdpc3RlcmVkIHRvIG9wZXJhdGUgaW4gSW5kaWEsIHVwIGZyb20gMzIwIGJldHdlZW4gMjAxOSBhbmQgMjAyMS4gVGhlcmUgYXJlIG5vdyBvdmVyIDEsNTAwIGdsb2JhbCBjYXBhYmlsaXR5IGNlbnRlcnMgaW4gdGhlIGNvdW50cnksIGFib3V0IDYwIHBlcmNlbnQgb2Ygd2hpY2ggZm9jdXMgb24gSVQsIGJ1c2luZXNzIHByb2Nlc3MgbWFuYWdlbWVudCwgb3IgZW5naW5lZXJpbmcsIHJlc2VhcmNoLCBhbmQgZGV2ZWxvcG1lbnQuIDEyIEFuYWx5c3RzIHByZWRpY3QgdGhhdCBjb21wYW5pZXMgd2lsbCAuLi4gJm5ic3A7Jm5ic3A7Jm5ic3A7IHd3dy5tY2tpbnNleS5jb20vaW5kdXN0cmllcy9pbmR1c3RyaWFscy9vdXItaW5zaWdodHMvaW5kaWEtdGhlLXByb21pc2UtYW5kLXBvc3NpYmlsaXRpZXMtZm9yLWdsb2JhbC1jb21wYW5pZXMgJm5ic3A7ICZuYnNwOyAzLiZuYnNwOyAyMDI1IGFuZCBCZXlvbmQ6IDggQnVzaW5lc3MgVHJlbmRzIEluZGlhbiBMZWFkZXJzIE11c3QgUHJlcGFyZSBGb3IgJm5ic3A7Jm5ic3A7Jm5ic3A7IEV4cGxvcmUgOCBwb3dlcmZ1bCBidXNpbmVzcyB0cmVuZHMgSW5kaWFuIGxlYWRlcnMgbXVzdCBwcmVwYXJlIGZvciBpbiAyMDI1IGFuZCBiZXlvbmQuIFN0YXkgYWhlYWQgb2YgY2hhbmdlIHdpdGggYWN0aW9uYWJsZSBpbnNpZ2h0cyBhbmQgZnV0dXJlLXJlYWR5IHN0cmF0ZWdpZXMuICZuYnNwOyZuYnNwOyZuYnNwOyB3d3cudGhlY2VvLmluL2J1c2luZXNzL2J1c2luZXNzLXRyZW5kcy1mb3ItaW5kaWFuLWxlYWRlcnMgJm5ic3A7ICZuYnNwOyA0LiZuYnNwOyBEb2luZyBCdXNpbmVzcyBJbi4uLiAyMDI1IC0gSW5kaWEgfCBHbG9iYWwgUHJhY3RpY2UgR3VpZGVzIHwgQ2hhbWJlcnMgLi4uICZuYnNwOyZuYnNwOyZuYnNwOyBJbiAyMDI1ICwgSW5kaWEgaXMgbm90IG1lcmVseSBhbiBlbWVyZ2luZyBtYXJrZXQgLSBpdCBpcyBhIHBvd2VyaG91c2Ugb2YgaW52ZXN0bWVudCBvcHBvcnR1bml0aWVzLiBXaXRoIGl0cyBkeW5hbWljIGVjb25vbXksIHByby0gYnVzaW5lc3MgcG9saWNpZXMsIGFuZCBzdGVhZGZhc3QgY29tbWl0bWVudCB0byBncm93dGgsIEluZGlhIHN0YW5kcyBvdXQgYXMgdGhlIG1vc3QgY29tcGVsbGluZyBkZXN0aW5hdGlvbiBmb3IgZ2xvYmFsIGludmVzdG9ycyBzZWVraW5nIHN1c3RhaW5hYmxlLCBoaWdoLXJldHVybiBvcHBvcnR1bml0aWVzLiAmbmJzcDsmbmJzcDsmbmJzcDsgcHJhY3RpY2VndWlkZXMuY2hhbWJlcnMuY29tL3ByYWN0aWNlLWd1aWRlcy9kb2luZy1idXNpbmVzcy1pbi0yMDI1L2luZGlhL3RyZW5kcy1hbmQtZGV2ZWxvcG1lbnRzICZuYnNwOyAmbmJzcDsgNS4mbmJzcDsgMjAyNTogV2hhdCBjYW4gdGhlIEluZGlhbiBidXNpbmVzcyB3b3JsZCBleHBlY3Q/LCBFVENGTyAmbmJzcDsmbmJzcDsmbmJzcDsgSW5kaWFuIEJ1c2luZXNzZXM6IEFzIHdlIHN0ZXAgaW50byAyMDI1ICwgc2Vhc29uZWQgZmluYW5jZSBleHBlcnQgUm9iaW4gQmFuZXJqZWUgcHJvdmlkZXMgYSBjbGVhci1leWVkIGFzc2Vzc21lbnQgb2YgSW5kaWEmI3gyNztzIGVjb25vbWljIHByb3NwZWN0cy4gSW4gdGhpcyBpbnNpZ2h0ZnVsIHBpZWNlLCBoZSBuYXZpZ2F0ZXMga2V5IHRyZW5kcyBhbmQgY2hhbGxlbmdlcywgb2ZmZXJpbmcgYSBiYWxhbmNlZCBvdXRsb29rIG9uIGJ1c2luZXNzICwgZ3Jvd3RoLCBhbmQgZ2xvYmFsIGluZmx1ZW5jZXMuICZuYnNwOyZuYnNwOyZuYnNwOyBjZm8uZWNvbm9taWN0aW1lcy5pbmRpYXRpbWVzLmNvbS9uZXdzL3N0cmF0ZWd5LW9wZXJhdGlvbnMvMjAyNS13aGF0LWNhbi10aGUtaW5kaWFuLWJ1c2luZXNzLXdvcmxkLWV4cGVjdC8xMTY4Nzg0NDggJm5ic3A7ICZuYnNwOyA2LiZuYnNwOyAyMCBGdXR1cmUgQnVzaW5lc3MgSWRlYXMgaW4gSW5kaWEgMjAyNSB8IEhpZ2gtR3Jvd3RoIFNlY3RvcnMgJm5ic3A7Jm5ic3A7Jm5ic3A7IERpc2NvdmVyIDIwIGdhbWUtY2hhbmdpbmcgZnV0dXJlIGJ1c2luZXNzIGlkZWFzIGluIEluZGlhIGZvciAyMDI1ICwgZnJvbSBBSSB0byByZW5ld2FibGUgZW5lcmd5LiBTdGF5IGFoZWFkIHdpdGggaGlnaC1ncm93dGggb3Bwb3J0dW5pdGllcy4gJm5ic3A7Jm5ic3A7Jm5ic3A7IHd3dy5kZWtvZGVyLmNvbS9hcnRpY2xlLzIwLWdhbWUtY2hhbmdpbmctZnV0dXJlLWJ1c2luZXNzLWlkZWFzLWluLWluZGlhLWZvci0yMDI1ICZuYnNwOyAmbmJzcDsgNy4mbmJzcDsgMjAyNSBCdXNpbmVzcyBUcmVuZHM6IFRoZSBFdm9sdmluZyBMYW5kc2NhcGUgb2YgRW50cmVwcmVuZXVyc2hpcCBpbiBJbmRpYSAmbmJzcDsmbmJzcDsmbmJzcDsgU3VjY2VzcyB3aWxsIGRlcGVuZCBvbiBhZGFwdGFiaWxpdHksIGlubm92YXRpb24sIGFuZCBzdHJhdGVnaWMgZm9yZXNpZ2h0LiBJbmRpYSYjeDI3O3MgQnVzaW5lc3MgTGFuZHNjYXBlIGluIDIwMjUgSW5kaWEmI3gyNztzIGVjb25vbXkgaXMgc2V0IHRvIGdyb3cgYmV0d2VlbiA2LjUlIGFuZCA3JSwgZnVlbGVkIGJ5IGRvbWVzdGljIGRlbWFuZCwgZ292ZXJubWVudCBwb2xpY2llcywgYW5kIGdsb2JhbCB0cmVuZHMgLiAmbmJzcDsmbmJzcDsmbmJzcDsgYnVzaW4ifQ==\").decode()\ndata = node_1_output\nprint('Market Trends:')\nprint(data[:2000])"
}

def run(args):
    import io, contextlib, json as _json
    code = args.get("code", args.get("script", "")).strip()
    input_data = args.get("input", "")
    if not code:
        return "Error: no code provided in args"
    buf = io.StringIO()
    local_vars = {"INPUT": input_data, "json": _json}
    try:
        compiled = compile(code, "<amsab>", "exec")
    except SyntaxError as e:
        lines = code.split("\n")
        bad = lines[e.lineno - 1].strip() if e.lineno and e.lineno <= len(lines) else "?"
        raise SyntaxError(f"line {e.lineno}: {e.msg} — code: {bad!r}")
    with contextlib.redirect_stdout(buf):
        exec(compiled, local_vars)
    stdout = buf.getvalue().strip()
    output_var = local_vars.get("OUTPUT", "")
    result = stdout or (str(output_var) if output_var else "")
    return result if result else "(no output — add print() calls to your code)"

if __name__ == "__main__":
    try:
        result = run(ARGS)
        print(json.dumps({"status": "ok", "output": result}))
    except Exception as exc:
        print(json.dumps({"status": "error", "error": str(exc)}))
        sys.exit(1)
