# AMSAB Worker — auto-generated runner
# Task: extract recipe details from search results
# Tool: python_interpreter
import json, sys, os

ARGS = {
  "code": "import base64 as _b64\nnode_1_output = _b64.b64decode(\"eyJzdGF0dXMiOiAib2siLCAib3V0cHV0IjogImF1dGhlbnRpYyBiaXJ5YW5pIHJlY2lwZSBpbmdyZWRpZW50cyBzdGVwcyBhdCBEdWNrRHVja0dvICZuYnNwOyBEdWNrRHVja0dvICZuYnNwOyBBbGwgUmVnaW9ucyBBcmdlbnRpbmEgQXVzdHJhbGlhIEF1c3RyaWEgQmVsZ2l1bSAoZnIpIEJlbGdpdW0gKG5sKSBCcmF6aWwgQnVsZ2FyaWEgQ2FuYWRhIChlbikgQ2FuYWRhIChmcikgQ2F0YWxvbmlhIENoaWxlIENoaW5hIENvbG9tYmlhIENyb2F0aWEgQ3plY2ggUmVwdWJsaWMgRGVubWFyayBFc3RvbmlhIEZpbmxhbmQgRnJhbmNlIEdlcm1hbnkgR3JlZWNlIEhvbmcgS29uZyBIdW5nYXJ5IEljZWxhbmQgSW5kaWEgKGVuKSBJbmRvbmVzaWEgKGVuKSBJcmVsYW5kIElzcmFlbCAoZW4pIEl0YWx5IEphcGFuIEtvcmVhIExhdHZpYSBMaXRodWFuaWEgTWFsYXlzaWEgKGVuKSBNZXhpY28gTmV0aGVybGFuZHMgTmV3IFplYWxhbmQgTm9yd2F5IFBha2lzdGFuIChlbikgUGVydSBQaGlsaXBwaW5lcyAoZW4pIFBvbGFuZCBQb3J0dWdhbCBSb21hbmlhIFJ1c3NpYSBTYXVkaSBBcmFiaWEgU2luZ2Fwb3JlIFNsb3Zha2lhIFNsb3ZlbmlhIFNvdXRoIEFmcmljYSBTcGFpbiAoY2EpIFNwYWluIChlcykgU3dlZGVuIFN3aXR6ZXJsYW5kIChkZSkgU3dpdHplcmxhbmQgKGZyKSBUYWl3YW4gVGhhaWxhbmQgKGVuKSBUdXJrZXkgVVMgKEVuZ2xpc2gpIFVTIChTcGFuaXNoKSBVa3JhaW5lIFVuaXRlZCBLaW5nZG9tIFZpZXRuYW0gKGVuKSBBbnkgVGltZSBQYXN0IERheSBQYXN0IFdlZWsgUGFzdCBNb250aCBQYXN0IFllYXIgJm5ic3A7ICZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOyAmbmJzcDsgMS4mbmJzcDsgQXV0aGVudGljIENoaWNrZW4gQmlyeWFuaSBSZWNpcGUgU3RlcCBieSBTdGVwOiBVbHRpbWF0ZSBGbGF2b3IgR3VpZGUgJm5ic3A7Jm5ic3A7Jm5ic3A7IFRoaXMgYXV0aGVudGljIGNoaWNrZW4gYmlyeWFuaSByZWNpcGUgYnJlYWtzIGRvd24gZXZlcnkgc3RlcCAsIG1ha2luZyBpdCBlYXN5IGZvciB5b3UgdG8gY3JlYXRlIGEgZmxhdm9yZnVsLCBhcm9tYXRpYyBkaXNoIGF0IGhvbWUuIEltYWdpbmUgdGhlIHJpY2ggc3BpY2VzLCB0ZW5kZXIgY2hpY2tlbiwgYW5kIGZsdWZmeSByaWNlIGNvbWluZyB0b2dldGhlciBwZXJmZWN0bHlcdTIwMTRyaWdodCBmcm9tIHlvdXIgb3duIGtpdGNoZW4uIEtlZXAgcmVhZGluZywgYW5kIHlvdSYjeDI3O2xsIGRpc2NvdmVyIHNpbXBsZSB0aXBzIHRoYXQgd2lsbCB0dXJuIHlvdXIgYmlyeWFuaSBpbnRvIGEgZmFtaWx5IGZhdm9yaXRlLiAmbmJzcDsmbmJzcDsmbmJzcDsgY2hpY2tlbmNvb2t0ZW1wLmNvbS9hdXRoZW50aWMtY2hpY2tlbi1iaXJ5YW5pLXJlY2lwZS1zdGVwLWJ5LXN0ZXAvICZuYnNwOyAmbmJzcDsgMi4mbmJzcDsgQ2hpY2tlbiBCaXJ5YW5pICggU3RlcC1ieS1zdGVwIENoaWNrZW4gQmlyeWFuaSkgLSBSdWNoaXNraXRjaGVuICZuYnNwOyZuYnNwOyZuYnNwOyBUaGUgdHJhZGl0aW9uYWwgQ2hpY2tlbiBCaXJ5YW5pIHJlY2lwZSBhcHBlYXJzIGludHJpY2F0ZSBvd2luZyB0byB0aGUgZXh0ZW5zaXZlIGxpc3Qgb2YgaW5ncmVkaWVudHMgYW5kIGVsYWJvcmF0ZSBjb29raW5nIHRlY2huaXF1ZXMsIHdoaWNoIHN0b3BzIG1hbnkgZnJvbSBhdHRlbXB0aW5nIGl0IGF0IGhvbWUuIEJ1dCwgSSBoYXZlIHRyaWVkIHRvIGRpc3BlbCB0aGF0IG15dGggYW5kIHNpbXBsaWZpZWQgdGhlIHByb2Nlc3Mgb2YgbWFraW5nIGF1dGhlbnRpYyBiaXJ5YW5pIHRvIGhlbHAgeW91IGNyZWF0ZSB0aGlzIGN1bGluYXJ5IG1hc3RlcnBpZWNlIHdpdGggY29uZmlkZW5jZS4gJm5ic3A7Jm5ic3A7Jm5ic3A7IHd3dy5ydWNoaXNraXRjaGVuLmNvbS9jaGlja2VuLWJpcnlhbmkvICZuYnNwOyAmbmJzcDsgMy4mbmJzcDsgQXV0aGVudGljIENoaWNrZW4gQmlyeWFuaSBSZWNpcGUgfCBTdGVwLWJ5LVN0ZXAgR3VpZGUgJm5ic3A7Jm5ic3A7Jm5ic3A7IEF1dGhlbnRpYyBDaGlja2VuIEJpcnlhbmkgUmVjaXBlIHdpdGggYmFzbWF0aSByaWNlLCB0ZW5kZXIgY2hpY2tlbiwgYW5kIHJpY2ggc3BpY2VzLiBFYXN5IHN0ZXAgLWJ5LSBzdGVwIG1ldGhvZCBmb3IgcGVyZmVjdCBiaXJ5YW5pIGV2ZXJ5IHRpbWUuICZuYnNwOyZuYnNwOyZuYnNwOyBmYWhvcmlhLmNvbS9hdXRoZW50aWMtY2hpY2tlbi1iaXJ5YW5pLXJlY2lwZS1wZXJmZWN0LWZsYXZvci8gJm5ic3A7ICZuYnNwOyA0LiZuYnNwOyBIb3cgVG8gTWFrZSBBdXRoZW50aWMgQ2hpY2tlbiBCaXJ5YW5pIEF0IEhvbWUgJm5ic3A7Jm5ic3A7Jm5ic3A7IEFmdGVyIHllYXJzIG9mIHRlc3RpbmcgYW5kIHBlcmZlY3RpbmcgSG93IFRvIE1ha2UgQXV0aGVudGljIENoaWNrZW4gQmlyeWFuaSBBdCBIb21lIGZpbmFsbHkgd2UgZ290IGl0ISBEb24mI3gyNzt0IGJlIGludGltaWRhdGVkIGJ5IHRoZSBpbmdyZWRpZW50IGxpc3QsIEkgaW5jbHVkZWQgaGVscGZ1bCBzdGVwIC1ieS0gc3RlcCBpbnN0cnVjdGlvbnMgdG8gZW5zdXJlIHlvdSBjYW4gZWFzaWx5IGZvbGxvdyBhbG9uZy4gSW4gdGhpcyBkaXNoLCBsYXllcnMgb2YgcmljZSwgY2hpY2tlbiwgYW5kIGdyYXZ5IGNvbWJpbmUgd2l0aCBmcmVzaCBoZXJicyBhbmQgaG9tZW1hZGUgYmlyeWFuaSBtYXNhbGEgKHNwaWNlIGJsZW5kKS4gJm5ic3A7Jm5ic3A7Jm5ic3A7IHR3b2Nsb3Zlc2luYXBvdC5jb20vaG93LXRvLW1ha2UtYXV0aGVudGljLWNoaWNrZW4tYmlyeWFuaS1hdC1ob21lLyAmbmJzcDsgJm5ic3A7IDUuJm5ic3A7IEF1dGhlbnRpYyBJbmRpYW4gQ2hpY2tlbiBCaXJ5YW5pIC0gc3RlcCBieSBzdGVwIG1lYWxzICZuYnNwOyZuYnNwOyZuYnNwOyBBdXRoZW50aWMgSW5kaWFuIFJlc3RhdXJhbnQtU3R5bGUgQ2hpY2tlbiBCaXJ5YW5pIGJyaW5ncyB0aGUgcmljaCwgYXJvbWF0aWMgZmxhdm9ycyBvZiBjbGFzc2ljIEluZGlhbiBjdWlzaW5lIHJpZ2h0IGludG8geW91ciBraXRjaGVuLiBUaGlzIGxheWVyZWQgcmljZSBkaXNoIGNvbWJpbmVzIHRlbmRlciBwaWVjZXMgb2YgY2hpY2tlbiB3aXRoIGZyYWdyYW50IHNwaWNlcyBhbmQgZnJlc2ggaGVyYnMsIG1ha2luZyBpdCBhIHBlcmZlY3QgbWVhbCBmb3IgYW55IGRheSB3aGVuIHlvdSB3YW50IHNvbWV0aGluZyBib3RoIGNvbWZvcnRpbmcgYW5kIGV4Y2l0aW5nLiAmbmJzcDsmbmJzcDsmbmJzcDsgc3RlcGJ5c3RlcG1lYWxzLmNvbS9yZWNpcGVzL2F1dGhlbnRpYy1pbmRpYW4tY2hpY2tlbi1iaXJ5YW5pICZuYnNwOyAmbmJzcDsgNi4mbmJzcDsgQXV0aGVudGljIEJpcnlhbmkgUmVjaXBlIHwgU3RlcC1ieS1TdGVwIEd1aWRlIHdpdGggQXNoaXNoIE1hc2FsZSBTcGljZXMgLi4uICZuYnNwOyZuYnNwOyZuYnNwOyBBdXRoZW50aWMgQ2hpY2tlbiBCaXJ5YW5pIFJlY2lwZSBCaXJ5YW5pIGlzIGEgY2xhc3NpYywgZmxhdm9yZnVsIEluZGlhbiBkaXNoIHRoYXQmI3gyNztzIGEgZmF2b3JpdGUgYWNyb3NzIHRoZSBnbG9iZS4gSXQmI3gyNztzIGtub3duIGZvciBpdHMgZnJhZ3JhbnQgcmljZSwgYXJvbWF0aWMgc3BpY2VzLCBhbmQgdGVuZGVyIGNoaWNrZW4sIG1ha2luZyBpdCBhIGdvLXRvIGZvciBzcGVjaWFsIG9jY2FzaW9ucyBvciBmYW1pbHkgZGlubmVycy4gJm5ic3A7Jm5ic3A7Jm5ic3A7IGFzaGlzaG1hc2FsZS5jb20vYmlyeWFuaS1yZWNpcGUvICZuYnNwOyAmbmJzcDsgNy4mbmJzcDsgQXV0aGVudGljIEluZGlhbiBSZXN0YXVyYW50IFN0eWxlIENoaWNrZW4gQmlyeWFuaSAtIFNhdm9ydGFsZXMgJm5ic3A7Jm5ic3A7Jm5ic3A7IEF1dGhlbnRpYyBJbmRpYW4gUmVzdGF1cmFudCBTdHlsZSBDaGlja2VuIEJpcnlhbmkgaXMgbW9yZSB0aGFuIGp1c3QgZm9vZFx1MjAxNGl0JiN4Mjc7cyB0cmFkaXRpb24sIGNlbGVicmF0aW9uLCBhbmQgY29tZm9ydCBpbiBldmVyeSBiaXRlLiBUaGlzIHJlY2lwZSBicmluZ3MgdG9nZXRoZXIgZXZlcnl0aGluZyB5b3UgbG92ZSBhYm91dCBiaXJ5YW5pIDogbGF5ZXJlZCBmbGF2b3JzLCBwZXJmZWN0bHkgY29va2VkIHJpY2UsIGFuZCBqdWljeSwgc3BpY2VkIGNoaWNrZW4uICZuYnNwOyZuYnNwOyZuYnNwOyBzYXZvIn0=\").decode()\ndata = node_1_output\nprint('Biryani Recipe Ingredients and Steps: ')\nfor i in range(0, len(data), 5):\n    print(data[i:i+5])"
}

def run(args):
    import io, contextlib, json as _json
    code = args.get("code", args.get("script", "")).strip()
    input_data = args.get("input", "")
    if not code:
        return "Error: no code provided in args"
    buf = io.StringIO()
    local_vars = {"INPUT": input_data, "json": _json}
    try:
        compiled = compile(code, "<amsab>", "exec")
    except SyntaxError as e:
        lines = code.split("\n")
        bad = lines[e.lineno - 1].strip() if e.lineno and e.lineno <= len(lines) else "?"
        raise SyntaxError(f"line {e.lineno}: {e.msg} — code: {bad!r}")
    with contextlib.redirect_stdout(buf):
        exec(compiled, local_vars)
    stdout = buf.getvalue().strip()
    output_var = local_vars.get("OUTPUT", "")
    result = stdout or (str(output_var) if output_var else "")
    return result if result else "(no output — add print() calls to your code)"

if __name__ == "__main__":
    try:
        result = run(ARGS)
        print(json.dumps({"status": "ok", "output": result}))
    except Exception as exc:
        print(json.dumps({"status": "error", "error": str(exc)}))
        sys.exit(1)
